# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
  Product.delete_all
Product.create(image_url:'rails.png', item:'Dining Table', specifications: '55.1"" X 39.4"" with two 19.7 extension plates', wood_used: 'Natural Oak', designer: 'Ben Brady', price: 800)
Product.create(image_url:'rails.png', item:'Dining Table', specifications: '46.9" X29.1" ; a hard wearing natural material', wood_used: 'Solid birch wood', designer: 'Ben Brady', price:100.00)
Product.create(image_url:'rails.png', item:'Dining Table', specifications: '30.3" X  74.8" X 47.2"  table with splayed legs and soft curved lines', wood_used: 'Solid birch wood', designer:'Karen Osaka', price:869.00)
Product.create(image_url:'rails.png', item:' Dining Table', specifications: '70.2"" X 74.1 groove retailing with sideboard tops with quality metal handles', wood_used: ' Beech Wood ', designer: ' Karen Osaka', price:500 )
Product.create(image_url:'rails.png', item:' Dining Table ', specifications: '42" X 72 amish modern solid wood', wood_used: 'Lyptus Solid Wood', designer: ' Steve Austin', price:1000)
Product.create(image_url:'rails.png', item:' Dining Table', specifications: ' 46.8" X 33.15 X 29.64 finished in satin lacquer with grain shine suitable for modern home.', wood_used: 'Oak Veneer', designer: ' Steve Austin', price:360 )
Product.create(image_url:'rails.png', item:' Dining Table', specifications: ' 72"  diameter top with a reverse-diamond 4-piece layup with a pedestal c legs.', wood_used: ' Mahogany Dark Walnut', designer: ' Steve Austin', price:750 )
Product.create(image_url:'rails.png', item:' Dining Table', specifications: ' 35.1" X 30.4" X 29.64" modern contemporary shaker design with drawer boxes and cabinet backs made of Tung Wood.', wood_used: ' Ash', designer: ' Steve Austin', price:950 )
Product.create(image_url:'rails.png', item:' Dining Table', specifications: ' 62.4" X 35.1" X 30.42" contemporary canvas for the natural beauty of the oak.', wood_used: 'Straight Oak', designer: ' Karen Osaka', price:1200 )
Product.create(image_url:'rails.png', item:' Dining Table', specifications: ' 70.59" X 37.44" X 30.03" adapted shabby chic to New England modern contemporary style.', wood_used: 'Knotty Pine', designer: 'Karen Osaka', price:950 )
Product.create(image_url:'rails.png', item:' Dining Chair ', specifications: ' 30.31" X 18.7" heavy duty with solid beech frame.', wood_used: ' Dark Oak', designer: ' Ben Brady', price:89)
Product.create(image_url:'rails.png', item:' Dining Chair ', specifications: ' 32.48" X 16.54" heat spray polished and have stain resistant acid catalyst lacquer.', wood_used: ' Wenge ', designer: ' Ben Brady', price:126 )
Product.create(image_url:'rails.png', item:' Dining Chair ', specifications: ' 37.4" X  18.11" chair with legs sprayed in a Regency finish.', wood_used: ' Rich Mahogany', designer: ' Karen Osaka', price:65 )
Product.create(image_url:'rails.png', item:' Dining Chair ', specifications: ' 33.46" X 16.34" sprayed using good lacquer and available with any fabric.', wood_used: ' Cherry Wood', designer: ' Karen Osaka', price:60)
Product.create(image_url:'rails.png', item:' Dining Chair ', specifications: ' 35.04" X 19.69" white washed finish with solid hardwood frame.', wood_used: ' Solid hard Wood', designer: ' Steve Austin', price:68 )
Product.create(image_url:'rails.png', item:' Dining Chair', specifications: ' 29.72 " X 22.83"  strong construction glued and pinned joints with cmhr 40 high density foam.', wood_used: ' Teak', designer: ' Steve Austin', price:165)
Product.create(image_url:'rails.png', item:' Dining Chair', specifications: ' 31.1 " X 15.35" ideal for cafes and solid strong frames.', wood_used: ' Solid Beech', designer: ' Steve Austin', price: 75 )
Product.create(image_url:'rails.png', item:' Dining Chair', specifications: ' 37.4" X 18.11" reinforced H Section construction frame for extra strength.', wood_used: ' Natural Oak', designer:' Steve Austin', price:45 )
Product.create(image_url:'rails.png', item:' Dining Chair ', specifications: ' 34.65" X 18.7" manufactured to the highest quality in the Italian design.', wood_used: ' Rose Wood', designer: ' Suzanne Daly', price:140)
Product.create(image_url:'rails.png', item:' Dining Chair ', specifications: ' 35.04" X 19.69" heavy duty chairs with fully assembled hardwood frame.', wood_used: ' Rustic Oak finish', designer: ' Suzanne Daly', price:99)
Product.create(image_url:'rails.png', item:' Bed Frame ', specifications: ' 4 ft X 6 ins double with a rustic style.', wood_used: ' Solid Oak', designer: ' Ben Brady', price:200)
Product.create(image_url:'rails.png', item:' Bed Frame ', specifications: ' 54" X 43.29" with feature stud detail and available in various sizes.', wood_used: ' Waxed Pine', designer: ' Ben Brady', price:179)
Product.create(image_url:'rails.png', item:' Bed Frame', specifications: ' 58.89" X  78.78" X 42.90" with a double bed measurement.', wood_used: ' Solid Pine', designer: ' Karen Osaka', price:205)
Product.create(image_url:'rails.png', item:' Bed Frame ', specifications: ' 85.02" X 63.96" X 44.85" chunky tops and brass cup handes with attractive design feature.', wood_used: 'Solid Pine', designer: 'Suzanne Daly', price:360 )
Product.create(image_url:'rails.png', item:' Bed Frame ', specifications: ' 60" kingsize bed with lots of accessories such as drawers and blanket boxes.', wood_used: ' cherry wood', designer: 'Suzanne Daly', price:250 )
Product.create(image_url:'rails.png', item:' Bed Frame ', specifications: '72 " a curved headboard and footboard matched straight slats.', wood_used: ' Solid Oak', designer: ' Steve Austin', price:350)
Product.create(image_url:'rails.png', item:' Bed Frame ', specifications: ' 60.0" venner with a satin ivory finish slat bed.', wood_used: ' solid wood', designer: ' Steve Austin', price:185)
Product.create(image_url:'rails.png', item:' Bed Frame ', specifications: ' 4 ft. 6ins standard size bed finished with raised paneling and pewter handles.', wood_used: ' mahogany', designer: ' Steve Austin', price:485 )
Product.create(image_url:'rails.png', item:' Bed Frame ', specifications: ' 48.0"  simple design with clean lines and luxurious finish that will stand the test of time.', wood_used: ' Solid Oak', designer: ' Suzanne Daly', price:222 )
Product.create(image_url:'rails.png', item:'Bed Frame ', specifications: ' 36.0" country traditional style that suits all kinds of bedroom designs.', wood_used: ' solid pine', designer: ' Suzanne Daly', price:99 )
Product.create(image_url:'rails.png', item:' Kitchen Unit ', specifications: ' A timeless style of kitchen and easy clean stylish woodgrain finish.', wood_used: ' Oak', designer: ' Ben Brady', price:1200)
Product.create(image_url:'rails.png', item:' Kitchen Unit ', specifications: ' Premium grade wood grain that complemented with stainless stell appliances.', wood_used: ' Black Walnut', designer: ' Ben Brady', price: 1352 )
Product.create(image_url:'rails.png', item:' Kitchen Unit ', specifications: ' Square Melamine style that complemented with natural wooden flooring.', wood_used: ' solid wood oak', designer: ' Karen Osaka', price:1563 )
Product.create(image_url:'rails.png', item:' Kitchen Unit ', specifications: ' A blend of formica black granite and the shape square suits modern apartment settings.', wood_used: ' Knotty  Oak', designer: ' Karen Osaka', price:1860 )
Product.create(image_url:'rails.png', item:' Kitchen Unit ', specifications: ' A smooth and classic look that suits a big family.', wood_used: ' Latina Walnut', designer: ' Steve Austin', price:950 )
Product.create(image_url:'rails.png', item:' Kitchen Unit ', specifications: ' It is a dense, strong and smooth hardy wood that resists abrasion like in a kitchen.', wood_used: ' Hard Maple', designer: ' Steve Austin', price:1450)
Product.create(image_url:'rails.png', item:' Kitchen Unit ', specifications: ' It is a softer hardwoods with a lighter density that show dents more easily.', wood_used: ' Alder', designer: ' Steve Austin', price:775 )
Product.create(image_url:'rails.png', item:' Kitchen Unit ', specifications: ' The units are more stable in humid conditions so a popular alternative to traditional wood.', wood_used: ' Wood Veneer', designer: ' Steve Austin', price:885)
Product.create(image_url:'rails.png', item:' Kitchen Unit ', specifications: ' The wood could be hard and heavy so suits in open air environment.', wood_used: ' Hickory', designer: ' Suzanne Daly', price:456 )
Product.create(image_url:'rails.png', item:' Kitchen Unit ', specifications: ' It had a vast variations in colour so suits in the modern settings of the apartments units.', wood_used: ' Oak', designer: ' Suzanne Daly', price:399 )
Product.create(image_url:'rails.png', item:' Bathroom Unit ', specifications: ' 23.4" X 31.2" X 19.5" add a touch of luxury and extravagance to your bathroom.', wood_used: ' Solid Oak', designer: ' Ben Brady', price:380 )
Product.create(image_url:'rails.png', item:' Bathroom Unit ', specifications: ' 35.1" X 31.2" X 23.4" the natural colour and the design was handcrafted for authentication.', wood_used: ' Solid Wenge Oak', designer: ' Ben Brady', price:410 )
Product.create(image_url:'rails.png', item:' Bathroom Unit ', specifications: ' 34" X 60" is a quality crafted of rubber solid wood and oak veneer with wild beauty.', wood_used: ' Antique Oak', designer: ' Karen Osaka', price:1563 )
Product.create(image_url:'rails.png', item:' Bathroom Unit ', specifications: ' 60" X 20" will add smart storage to any bathroom in your home.', wood_used: ' Oak', designer: ' Karen Osaka', price:1860)
Product.create(image_url:'rails.png', item:' Bathroom Unit ', specifications: ' 35" X 37" beatiful combination of traditional and modern design.', wood_used: ' Solid Birch', designer: ' Steve Austin', price:750 )
Product.create(image_url:'rails.png', item:' Bathroom Unit ', specifications: ' 38" X 25"  emphasize the bold style that transform the bath with a striking sink vanity.', wood_used: ' Dark Walnut', designer: ' Steve Austin', price:370 )
Product.create(image_url:'rails.png', item:' Bathroom Unit ', specifications: ' 35" X 38" made from materials of lasting beauty and use.', wood_used: ' Dark Oak', designer: ' Steve Austin', price:480)
Product.create(image_url:'rails.png', item:' Bathroom Unit ', specifications: ' 35" X 37" features a rich finish, stately columns and arched accents.', wood_used: ' Mahogany', designer: ' Steve Austin', price:770 )
Product.create(image_url:'rails.png', item:' Bathroom Unit ', specifications: ' 36" X 40" X 20" beautiful brown finish that includes plenty of storage.', wood_used: ' Birch Veneer', designer: ' Suzanne Daly', price:556 )
Product.create(image_url:'rails.png', item:' Bathroom Unit  ', specifications: ' 31" add form and function that is perfect for traditional or transitional bathroom decor.', wood_used: ' Birch', designer: ' Suzanne Daly', price:499 )
Product.create(image_url:'rails.png', item:' Bedroom Furniture  ', specifications: ' bedroom package that includes wardrobes and drawers.', wood_used: ' Beech', designer: ' Ben Brady', price:200 )
Product.create(image_url:'rails.png', item:' Bedroom Furniture  ', specifications: ' 100 % wood package that include 2dr Wardrobe, 5dr Chest, 2dr Locker.', wood_used: ' Oak Veneer', designer: ' Ben Brady', price:480 )
Product.create(image_url:'rails.png', item:' Bedroom Furniture  ', specifications: ' 4 drawer chest, 1 drawer locker, 3 dr mirrored wardrobe.', wood_used: ' Beech', designer: ' Karen Osaka', price:300)
Product.create(image_url:'rails.png', item:' Bedroom Furniture  ', specifications: ' The chunky and rustic look adds a touch of charm to any bedroom.', wood_used: ' Solid Pine', designer: ' Karen Osaka', price:219 )
Product.create(image_url:'rails.png', item:'  Bedroom Furniture ', specifications: ' It is made up of solid rubber wood which is a hardwood family and is eco friendly.', wood_used: ' Maple', designer: ' Steve Austin', price:319 )
Product.create(image_url:'rails.png', item:' Bedroom Furniture   ', specifications: ' The traditional or contemporary look enhanced by the craftsman to reflects the current trends of effect.', wood_used: ' Solid Oak', designer: ' Steve Austin', price:449 )
Product.create(image_url:'rails.png', item:' Bedroom Furniture  ', specifications: ' 44.85" X 16.77" X 31.59" veneers in a sumptuous light lacquered finish.', wood_used: ' Solid White Oak', designer: ' Steve Austin', price:465 )
Product.create(image_url:'rails.png', item:' Bedroom Furniture   ', specifications: ' 50.70" X 19.11" X 32.76" chunky tops and frames add a strength of character to this county styled range.', wood_used: ' Pine', designer: ' Steve Austin', price:399 )
Product.create(image_url:'rails.png', item:' Bedroom Furniture   ', specifications: ' 53.43" X 16.77" X 29.64" minuet twin pedestal dressing table which is attractive.', wood_used: ' Rich Wenge', designer: ' Suzanne Daly', price:376  )
Product.create(image_url:'rails.png', item:' Bedroom Furniture   ', specifications: ' 40.68" X 18.72" X 30.42"   A simple 4 Drawer Dressing Table.', wood_used: ' Waxed Pine', designer: ' Suzanne Daly', price:112 )
Product.create(image_url:'rails.png', item:' Chest Of Drawers   ', specifications: ' 31.2" X 28.47" X 15.6"  smooth running drawer with pull-out stop.', wood_used: ' oak', designer: ' Ben Brady', price:55  )
Product.create(image_url:'rails.png', item:' Chest Of Drawers   ', specifications: ' 37.44" X 19.5" X 35.49"  chest of 4 drawers with hardwearing natural material.', wood_used: ' pine', designer: ' Ben Brady', price:238  )
Product.create(image_url:'rails.png', item:' Chest Of Drawers  ', specifications: ' 30.42" X 27.3" X 15.99"  chest of 2 drawers suitable for fixing on the wall of your home.', wood_used: ' birch', designer: ' Karen Osaka', price:69  )
Product.create(image_url:'rails.png', item:' Chest Of Drawers  ', specifications: ' 50.7" X 18.72"   chest of many drawers with add-on units  made of solid wood.', wood_used: ' pine', designer: ' Karen Osaka', price:453 )
Product.create(image_url:'rails.png', item:' Chest Of Drawers   ', specifications: ' 15.6" X 18.92" X 47.97"  chest of 6 drawers with mirror glass.', wood_used: ' birch verneer', designer: ' Steve Austin', price:95  )
Product.create(image_url:'rails.png', item:' Chest Of Drawers   ', specifications: ' 42.9" X 19.5" X 51.48"  chest of 6 drawers with extra roomy drawers for more storage space.', wood_used: ' wood fibres', designer: ' Steve Austin', price:205 )
Product.create(image_url:'rails.png', item:' Chest Of Drawers   ', specifications: ' 24.18" X 11.7" X 27.30"  chest of 3 drawers solid wood with untreated solid wood.', wood_used: ' pine', designer: ' Steve Austin', price:25)
Product.create(image_url:'rails.png', item:' Chest Of Drawers   ', specifications: ' 30.42" X 15.99" X 49.14"  chest of 2 drawers with easy looking colours.', wood_used: ' walnut', designer: ' Steve Austin', price:100 )
Product.create(image_url:'rails.png', item:' Chest Of Drawers  ', specifications: ' 42.12" X 19.5" X 37.05" chest of 3 drawers extra roomy drawers and more spaces for storage.', wood_used: ' Solid Pine', designer: ' Suzanne Daly', price:106 )
Product.create(image_url:'rails.png', item:' Chest Of Drawers  ', specifications: ' 30.81" X 48.0" X 103" chest of 4 drawers a sturdy yet clear acrylic lacquer.' , wood_used: ' Birch white', designer: ' Suzanne Daly', price:185 )


